config/routes.rb
Rails.application.routes.draw do
  root "artworks#index"
  resources :artworks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artwork.rb
class Artwork < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    @artworks = Artwork.all
  end

  def show
    @artwork = Artwork.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/create.html.erb
<h1>Artworks#create</h1>
<p>Find me in app/views/artworks/create.html.erb</p>

app/views/artworks/delete.html.erb
<h1>Artworks#delete</h1>
<p>Find me in app/views/artworks/delete.html.erb</p>

app/views/artworks/edit.html.erb
<h1>Artworks#edit</h1>
<p>Find me in app/views/artworks/edit.html.erb</p>

app/views/artworks/index.html.erb
<h1>All artworks</h1>
<ul>
  <% @artworks.each do |artwork| %>
    <li>
      <%= link_to artwork.title, artwork_path(artwork) %>
    </li>
  <% end %>
</ul>

app/views/artworks/new.html.erb
<h1>Artworks#new</h1>
<p>Find me in app/views/artworks/new.html.erb</p>

app/views/artworks/show.html.erb
<h1><%= @artwork.title %></h1>
<h3>by <%= @artwork.artist %>, <%= @artwork.year %></h3>
<%= image_tag @artwork.image_url, alt_text: @artwork.alt_text, class: "img-oval" %>
<!--sanitize prevents <p> tags from showing up in description-->
<p><%= sanitize @artwork.description %></p>

app/views/artworks/update.html.erb
<h1>Artworks#update</h1>
<p>Find me in app/views/artworks/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtworkApiPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>